❄️

diff --git a/bin/next-init b/bin/next-init
--- a/bin/next-init
+++ b/bin/next-init
@@ -2,14 +2,68 @@
 umask 0077
 set -ex
 
-if [ $# != 1 ]; then
-  echo 'Usage: next-init DIRNAME'
+if test -f package.json ; then
+  echo 'Error: package.json already exists' >&2
   exit 1
 fi
 
-npx create-next-app -- "$1"
+cat > package.json <<EOF
+{
+  "private": true,
+  "scripts": {
+    "dev": "next",
+    "build": "next build",
+    "start": "next start",
+    "docker:build": "docker build .",
+    "format": "prettier --write **/*.{js,jsx,ts,tsx,json,yaml,gql,md,html,css}",
+    "lint": "eslint --ext .js,.jsx,.ts,.tsx src/",
+    "build:precommit": "npm run build && echo >/dev/null"
+  },
+  "husky": {
+    "hooks": {
+      "pre-commit": "lint-staged"
+    }
+  },
+  "lint-staged": {
+    "*.{js,jsx,ts,tsx,json,yaml,gql,md,html,css}": [
+      "prettier --write",
+      "git add"
+    ],
+    "src/**/*.{js,jsx,ts,tsx}": [
+      "eslint --max-warnings 0"
+    ],
+    "*": [
+      "npm run build:precommit"
+    ]
+  },
+  "prettier": {
+    "semi": false,
+    "singleQuote": true,
+    "endOfLine": "lf",
+    "trailingComma": "all",
+    "printWidth": 100
+  },
+  "eslintConfig": {
+    "parser": "@typescript-eslint/parser",
+    "plugins": [
+      "@typescript-eslint"
+    ],
+    "extends": [
+      "eslint:recommended",
+      "plugin:@typescript-eslint/eslint-recommended",
+      "plugin:@typescript-eslint/recommended",
+      "prettier",
+      "prettier/@typescript-eslint"
+    ]
+  }
+}
+EOF
 
-cd "$1"
+npm i next react react-dom
+npm i @material-ui/core
+npm i -D typescript @types/node @types/react
+npm i -D husky lint-staged prettier
+npm i -D eslint @typescript-eslint/eslint-plugin @typescript-eslint/parser eslint-config-prettier
 
 npx next telemetry disable
 
@@ -19,8 +73,16 @@ module.exports = {
 }
 EOF
 
+cat > .prettierignore <<EOF
+/.next/
+/cache/
+/node_modules/
+EOF
+
+# Next.JS will automatically populate this file
 touch tsconfig.json
 
-for file in components/*.js pages/*.js ; do
-  mv "$file" $(echo "$file" | sed 's/\.js$/.tsx/')
-done
+mkdir pages public
+next-page pages/index.tsx
+
+npm run dev
diff --git a/bin/pulumi-init b/bin/pulumi-init
--- a/bin/pulumi-init
+++ b/bin/pulumi-init
@@ -2,4 +2,57 @@
 umask 0077
 set -ex
 
-pulumi new -c 'backend.url=file://.' typescript
+if ! test -d .git ; then
+  echo >&2 'Error: pulumi-init requires to be run in a git repository'
+  exit 1
+fi
+
+pulumi new typescript -fgy
+cat >> Pulumi.yaml <<EOF
+backend:
+  url: file://.
+EOF
+
+npm i
+npm i -D prettier husky lint-staged
+sed -i '/^}$/d' package.json
+cat >> package.json <<EOF
+  , "main": "src/index.ts",
+  "scripts": {
+    "format": "prettier --write **/*.{js,jsx,ts,tsx,json,yaml,gql,md,html,css}",
+    "pre-commit": "pulumi preview --expect-no-changes --non-interactive -s prod && echo >/dev/null"
+  },
+  "husky": {
+    "hooks": {
+      "pre-commit": "lint-staged"
+    }
+  },
+  "lint-staged": {
+    "*.{js,jsx,ts,tsx,json,yaml,gql,md,html,css}": [
+      "prettier --write",
+      "git add"
+    ],
+    "*": [
+      "npm run pre-commit"
+    ]
+  },
+  "prettier": {
+    "semi": false,
+    "singleQuote": true,
+    "endOfLine": "lf",
+    "trailingComma": "all"
+  }
+}
+EOF
+
+cat > .prettierignore <<EOF
+/.git/
+/node_modules/
+/bin/
+EOF
+
+npm run format
+
+mkdir src
+mv index.ts src/
+sed -Ei 's|^( +"files":) .+$|\1 ["src/**/*.ts"]|' tsconfig.json
