🦀

diff --git a/bin/install/vector b/bin/install/vector
--- a/bin/install/vector
+++ b/bin/install/vector
@@ -7,6 +7,6 @@ VERSION=$(curl -sS https://api.github.com/repos/timberio/vector/releases/latest 
 echo "VERSION=$VERSION"
 if [ $# = 1 ] && [ "$1" = 'version' ]; then exit 0; fi
 set -x
-curl -fLO https://github.com/timberio/vector/releases/download/"$VERSION"/vector-"${VERSION#v}"-amd64.deb
-dpkg -i vector-"${VERSION#v}"-amd64.deb || true # ignore systemd no present: Failed to connect to bus: Host is down
-rm vector-"${VERSION#v}"-amd64.deb
+curl -fLO https://github.com/timberio/vector/releases/download/"$VERSION"/vector-"${VERSION#v}"-"$(dpkg --print-architecture)".deb
+dpkg -i vector-"${VERSION#v}"-"$(dpkg --print-architecture)".deb || true # ignore systemd no present: Failed to connect to bus: Host is down
+rm vector-"${VERSION#v}"-"$(dpkg --print-architecture)".deb
